#!/bin/bash

rm -rf org/lantern/rtc/*.class
# Change directory to the PRODUCT_DIR (e.g. out/Debug).
export LD_LIBRARY_PATH=`pwd`

# The RHS value is replaced by the build action that copies this script to
# <(PRODUCT_DIR).
export JAVA_HOME=/usr/local/java/jdk1.7.0_45

export CLASSPATH='.:libs/libjingle_peerconnection.jar:libs/junit-4.11.jar'

${JAVA_HOME}/bin/javac -cp $CLASSPATH org/lantern/rtc/*.java
