#!/bin/bash

rm -rf org/lantern/rtc/*.class
# Change directory to the PRODUCT_DIR (e.g. out/Debug).
export LD_LIBRARY_PATH=`pwd`

# The RHS value is replaced by the build action that copies this script to
# <(PRODUCT_DIR).
export JAVA_HOME=/usr/local/java/jdk1.7.0_45

export CLASSPATH='.:libjingle_peerconnection.jar'

${JAVA_HOME}/bin/javac -cp $CLASSPATH org/lantern/rtc/*.java
${JAVA_HOME}/bin/java -cp $CLASSPATH org.lantern.rtc.LanternRTC $1
